name: Refresh stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

env:
  PYTHON_VERSION: "3.11.0"
  TOKEN: ${{ secrets.TOKEN }}
  LOGIN: ${{ github.repository_owner }}

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pdm
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-pep582: true

      - name: Install packages
        run: pdm install
      
      - name: Refresh stats
        run: pdm run run.py
      
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Refresh stats
          default_author: github_actions